name: lunarlander
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - matplotlib
  - numpy
  - swig # 关键：预先安装 SWIG 以编译 Box2D
  - pip
  - pip:
    - gymnasium[box2d]
    - pygame